//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.0
//     from Assets/Control Interface App/ControllerScripts/GameController.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Control Interface App/ControllerScripts/GameController.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @GameController: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @GameController()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameController"",
    ""maps"": [
        {
            ""name"": ""DriveControl"",
            ""id"": ""e5e5d280-958e-44dc-b7ee-5e2d80762027"",
            ""actions"": [
                {
                    ""name"": ""leftJoy"",
                    ""type"": ""Value"",
                    ""id"": ""7234f501-1f21-466d-8f1c-b44d38d99fcd"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""StickDeadzone"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""rightJoy"",
                    ""type"": ""Value"",
                    ""id"": ""3518dbae-2f15-4a5a-b590-2aab1bddf073"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""StickDeadzone"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""buttonEast"",
                    ""type"": ""Button"",
                    ""id"": ""bdc69f32-fe22-4ec3-a160-cc69355646d4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""buttonWest"",
                    ""type"": ""Button"",
                    ""id"": ""f5303fbc-c305-40d6-abe6-08e804f78123"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""buttonNorth"",
                    ""type"": ""Button"",
                    ""id"": ""6d6ac9a7-98db-47fe-b401-27fb93ef6782"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""buttonSouth"",
                    ""type"": ""Button"",
                    ""id"": ""f2d452ea-d044-4454-b6d8-ab07ab5ea008"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""dpadEast"",
                    ""type"": ""Button"",
                    ""id"": ""4003e283-b131-4d35-a4d3-c8ba0f036159"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""dpadWest"",
                    ""type"": ""Button"",
                    ""id"": ""d23cacb8-0220-4177-b53a-2ae820af60b8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""dpadNorth"",
                    ""type"": ""Button"",
                    ""id"": ""6bb4788b-db16-447e-b6c4-f2a1924a9566"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""dpadSouth"",
                    ""type"": ""Button"",
                    ""id"": ""8e3bfdc7-44f2-4e5c-a393-255e0168706a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""start"",
                    ""type"": ""Button"",
                    ""id"": ""031bfc97-93d8-4937-acd7-911b77c012c5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""select"",
                    ""type"": ""Button"",
                    ""id"": ""f0fd069d-e2c6-4832-b935-e458ba7711d1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""shoulderWest"",
                    ""type"": ""Button"",
                    ""id"": ""303f47dc-19af-4d82-8470-6c3985f9d3ad"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""shoulderEast"",
                    ""type"": ""Button"",
                    ""id"": ""d2a2a12c-718e-443e-af6d-749c4d926701"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""triggerEast"",
                    ""type"": ""Value"",
                    ""id"": ""17b8509c-d5b0-49b7-b880-6c7036064840"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""triggerWest"",
                    ""type"": ""Value"",
                    ""id"": ""b59e049b-c67b-4427-8123-a7b2ed3f0ae3"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""joystickEastButton"",
                    ""type"": ""Button"",
                    ""id"": ""cdff8ce5-43fb-4b3f-b8d6-7d88b26334ab"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""fe38a6ed-b9a6-4ff4-a8d4-6317f2c35cc6"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone"",
                    ""groups"": """",
                    ""action"": ""leftJoy"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""22a68926-5f23-443c-8fb6-22e8328ae7e5"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone"",
                    ""groups"": """",
                    ""action"": ""rightJoy"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b6e2d035-43a4-402c-b22e-8b3add0e8e39"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""buttonEast"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f49c0a2f-6f0f-4fa6-b7a7-b0de9d7420b6"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""buttonWest"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4a8a6e1f-b78b-49f4-8585-8c2c93f86a18"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""buttonNorth"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5dc7367a-acb9-424e-8373-18c93ec9d91e"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""buttonSouth"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""75579814-b70b-4bd6-a917-65c13a3a285c"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""dpadEast"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f64a2dde-25e9-4c64-9618-517328ea5a63"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""dpadWest"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f05b85bc-afc6-4578-937b-7c5ab9af77d5"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""dpadNorth"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2eafde30-b418-4297-b253-7b0c4aeb8c42"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""dpadSouth"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d3e8f8a4-4e48-4439-9b1b-8e1254550459"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""shoulderWest"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8a0881f3-a6c6-41d8-abcf-10ad4d4cb355"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""shoulderEast"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""995bece6-c93a-4d8e-8feb-00d91759fd1d"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""triggerEast"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3a7988ed-0d76-4510-b512-dac5ab4f469e"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""triggerWest"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6f7dd8ea-cdba-4753-b1d7-1dec4e0d0d5e"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""start"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9f63068e-473e-4246-8533-e9928da2877c"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9f14f65f-01b3-481a-b89a-caa1264c6f22"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""joystickEastButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""BoardControl"",
            ""id"": ""b7c0da5e-d23c-496a-aa31-8bc5a687cd54"",
            ""actions"": [
                {
                    ""name"": ""New action"",
                    ""type"": ""Button"",
                    ""id"": ""4e5c7c35-7ace-4164-9ed6-9a39954d6e45"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""9700d414-287f-416b-8e9e-b1953855a10c"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""New action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""KeyboardControl"",
            ""id"": ""5be4993b-5144-45bd-ab0b-184046fd6643"",
            ""actions"": [
                {
                    ""name"": ""onekey"",
                    ""type"": ""Button"",
                    ""id"": ""73f06b34-76ce-47db-8342-b07e0224a1bd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""twokey"",
                    ""type"": ""Button"",
                    ""id"": ""c8f6ce3f-645d-4435-b776-a3a7b3b51879"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""threekey"",
                    ""type"": ""Button"",
                    ""id"": ""344f5111-ec11-4477-a081-afbe0b2e5932"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""fourkey"",
                    ""type"": ""Button"",
                    ""id"": ""ca827380-0198-4304-82da-be89bc095084"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""fivekey"",
                    ""type"": ""Button"",
                    ""id"": ""f3d9792c-ac2f-493b-b612-7255a8d7ec55"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""sixkey"",
                    ""type"": ""Button"",
                    ""id"": ""021d83d6-da0a-4170-a16a-57a46f59891e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""sevenkey"",
                    ""type"": ""Button"",
                    ""id"": ""a78b63f6-9dfb-4a5e-9452-23fa67b24867"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""eightkey"",
                    ""type"": ""Button"",
                    ""id"": ""ddb43dd6-7291-4fde-b6ed-7ab901dc7290"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ninekey"",
                    ""type"": ""Button"",
                    ""id"": ""55db3e19-ebab-47f7-bbd3-ab4c51ff52b0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""zerokey"",
                    ""type"": ""Button"",
                    ""id"": ""d2e6e20d-8a6e-44c8-92cd-c821d5472474"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Enter"",
                    ""type"": ""Button"",
                    ""id"": ""9a878c63-d281-472f-89f8-8e54758913a5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""spacekey"",
                    ""type"": ""Button"",
                    ""id"": ""2bb3a272-254d-40a7-8076-86b6b81e2a30"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""backspacekey"",
                    ""type"": ""Button"",
                    ""id"": ""af88aed1-dc94-43f9-908b-be864de67d5b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""shiftkey"",
                    ""type"": ""Button"",
                    ""id"": ""4aa27a3e-72d7-4ee0-8b16-8f2498e29eae"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""69743324-2ef1-4c77-93eb-7d2f2004f0e6"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""onekey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f194297a-9f0f-44e0-8c3f-ac6c2785bbd4"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""twokey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""75e9d925-4aed-4181-89c7-e3f776feaa88"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""threekey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aedaa558-fdd1-45f3-8e6f-cd8a9830e5de"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""fourkey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7f9a993a-b200-44b6-a181-4915799dde07"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""fivekey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5ec3fd84-fb53-44fd-b401-bf57d638be76"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""sixkey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""563f3207-9e0f-444d-8379-c1794410ae77"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""sevenkey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2439bef1-38d1-4950-a475-0a4b69446adc"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""eightkey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c0f92fc8-e116-47ff-8a97-e125c9b80175"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ninekey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f7161b7a-7110-47e5-93e2-79c934b0270a"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""zerokey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2cb5fd6d-b042-495c-b4c4-dfb521971cdd"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Enter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e4f07303-3c56-41bc-9d7a-e6e6053802ab"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""spacekey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fd46bb74-6c8f-43b1-bcc4-28b70a65fb55"",
                    ""path"": ""<Keyboard>/backspace"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""backspacekey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8139c5f6-a6e0-4d93-b4b2-a9dfbc1d835c"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""shiftkey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // DriveControl
        m_DriveControl = asset.FindActionMap("DriveControl", throwIfNotFound: true);
        m_DriveControl_leftJoy = m_DriveControl.FindAction("leftJoy", throwIfNotFound: true);
        m_DriveControl_rightJoy = m_DriveControl.FindAction("rightJoy", throwIfNotFound: true);
        m_DriveControl_buttonEast = m_DriveControl.FindAction("buttonEast", throwIfNotFound: true);
        m_DriveControl_buttonWest = m_DriveControl.FindAction("buttonWest", throwIfNotFound: true);
        m_DriveControl_buttonNorth = m_DriveControl.FindAction("buttonNorth", throwIfNotFound: true);
        m_DriveControl_buttonSouth = m_DriveControl.FindAction("buttonSouth", throwIfNotFound: true);
        m_DriveControl_dpadEast = m_DriveControl.FindAction("dpadEast", throwIfNotFound: true);
        m_DriveControl_dpadWest = m_DriveControl.FindAction("dpadWest", throwIfNotFound: true);
        m_DriveControl_dpadNorth = m_DriveControl.FindAction("dpadNorth", throwIfNotFound: true);
        m_DriveControl_dpadSouth = m_DriveControl.FindAction("dpadSouth", throwIfNotFound: true);
        m_DriveControl_start = m_DriveControl.FindAction("start", throwIfNotFound: true);
        m_DriveControl_select = m_DriveControl.FindAction("select", throwIfNotFound: true);
        m_DriveControl_shoulderWest = m_DriveControl.FindAction("shoulderWest", throwIfNotFound: true);
        m_DriveControl_shoulderEast = m_DriveControl.FindAction("shoulderEast", throwIfNotFound: true);
        m_DriveControl_triggerEast = m_DriveControl.FindAction("triggerEast", throwIfNotFound: true);
        m_DriveControl_triggerWest = m_DriveControl.FindAction("triggerWest", throwIfNotFound: true);
        m_DriveControl_joystickEastButton = m_DriveControl.FindAction("joystickEastButton", throwIfNotFound: true);
        // BoardControl
        m_BoardControl = asset.FindActionMap("BoardControl", throwIfNotFound: true);
        m_BoardControl_Newaction = m_BoardControl.FindAction("New action", throwIfNotFound: true);
        // KeyboardControl
        m_KeyboardControl = asset.FindActionMap("KeyboardControl", throwIfNotFound: true);
        m_KeyboardControl_onekey = m_KeyboardControl.FindAction("onekey", throwIfNotFound: true);
        m_KeyboardControl_twokey = m_KeyboardControl.FindAction("twokey", throwIfNotFound: true);
        m_KeyboardControl_threekey = m_KeyboardControl.FindAction("threekey", throwIfNotFound: true);
        m_KeyboardControl_fourkey = m_KeyboardControl.FindAction("fourkey", throwIfNotFound: true);
        m_KeyboardControl_fivekey = m_KeyboardControl.FindAction("fivekey", throwIfNotFound: true);
        m_KeyboardControl_sixkey = m_KeyboardControl.FindAction("sixkey", throwIfNotFound: true);
        m_KeyboardControl_sevenkey = m_KeyboardControl.FindAction("sevenkey", throwIfNotFound: true);
        m_KeyboardControl_eightkey = m_KeyboardControl.FindAction("eightkey", throwIfNotFound: true);
        m_KeyboardControl_ninekey = m_KeyboardControl.FindAction("ninekey", throwIfNotFound: true);
        m_KeyboardControl_zerokey = m_KeyboardControl.FindAction("zerokey", throwIfNotFound: true);
        m_KeyboardControl_Enter = m_KeyboardControl.FindAction("Enter", throwIfNotFound: true);
        m_KeyboardControl_spacekey = m_KeyboardControl.FindAction("spacekey", throwIfNotFound: true);
        m_KeyboardControl_backspacekey = m_KeyboardControl.FindAction("backspacekey", throwIfNotFound: true);
        m_KeyboardControl_shiftkey = m_KeyboardControl.FindAction("shiftkey", throwIfNotFound: true);
    }

    ~@GameController()
    {
        UnityEngine.Debug.Assert(!m_DriveControl.enabled, "This will cause a leak and performance issues, GameController.DriveControl.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_BoardControl.enabled, "This will cause a leak and performance issues, GameController.BoardControl.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_KeyboardControl.enabled, "This will cause a leak and performance issues, GameController.KeyboardControl.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // DriveControl
    private readonly InputActionMap m_DriveControl;
    private List<IDriveControlActions> m_DriveControlActionsCallbackInterfaces = new List<IDriveControlActions>();
    private readonly InputAction m_DriveControl_leftJoy;
    private readonly InputAction m_DriveControl_rightJoy;
    private readonly InputAction m_DriveControl_buttonEast;
    private readonly InputAction m_DriveControl_buttonWest;
    private readonly InputAction m_DriveControl_buttonNorth;
    private readonly InputAction m_DriveControl_buttonSouth;
    private readonly InputAction m_DriveControl_dpadEast;
    private readonly InputAction m_DriveControl_dpadWest;
    private readonly InputAction m_DriveControl_dpadNorth;
    private readonly InputAction m_DriveControl_dpadSouth;
    private readonly InputAction m_DriveControl_start;
    private readonly InputAction m_DriveControl_select;
    private readonly InputAction m_DriveControl_shoulderWest;
    private readonly InputAction m_DriveControl_shoulderEast;
    private readonly InputAction m_DriveControl_triggerEast;
    private readonly InputAction m_DriveControl_triggerWest;
    private readonly InputAction m_DriveControl_joystickEastButton;
    /// <summary>
    /// Provides access to input actions defined in input action map "DriveControl".
    /// </summary>
    public struct DriveControlActions
    {
        private @GameController m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public DriveControlActions(@GameController wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "DriveControl/leftJoy".
        /// </summary>
        public InputAction @leftJoy => m_Wrapper.m_DriveControl_leftJoy;
        /// <summary>
        /// Provides access to the underlying input action "DriveControl/rightJoy".
        /// </summary>
        public InputAction @rightJoy => m_Wrapper.m_DriveControl_rightJoy;
        /// <summary>
        /// Provides access to the underlying input action "DriveControl/buttonEast".
        /// </summary>
        public InputAction @buttonEast => m_Wrapper.m_DriveControl_buttonEast;
        /// <summary>
        /// Provides access to the underlying input action "DriveControl/buttonWest".
        /// </summary>
        public InputAction @buttonWest => m_Wrapper.m_DriveControl_buttonWest;
        /// <summary>
        /// Provides access to the underlying input action "DriveControl/buttonNorth".
        /// </summary>
        public InputAction @buttonNorth => m_Wrapper.m_DriveControl_buttonNorth;
        /// <summary>
        /// Provides access to the underlying input action "DriveControl/buttonSouth".
        /// </summary>
        public InputAction @buttonSouth => m_Wrapper.m_DriveControl_buttonSouth;
        /// <summary>
        /// Provides access to the underlying input action "DriveControl/dpadEast".
        /// </summary>
        public InputAction @dpadEast => m_Wrapper.m_DriveControl_dpadEast;
        /// <summary>
        /// Provides access to the underlying input action "DriveControl/dpadWest".
        /// </summary>
        public InputAction @dpadWest => m_Wrapper.m_DriveControl_dpadWest;
        /// <summary>
        /// Provides access to the underlying input action "DriveControl/dpadNorth".
        /// </summary>
        public InputAction @dpadNorth => m_Wrapper.m_DriveControl_dpadNorth;
        /// <summary>
        /// Provides access to the underlying input action "DriveControl/dpadSouth".
        /// </summary>
        public InputAction @dpadSouth => m_Wrapper.m_DriveControl_dpadSouth;
        /// <summary>
        /// Provides access to the underlying input action "DriveControl/start".
        /// </summary>
        public InputAction @start => m_Wrapper.m_DriveControl_start;
        /// <summary>
        /// Provides access to the underlying input action "DriveControl/select".
        /// </summary>
        public InputAction @select => m_Wrapper.m_DriveControl_select;
        /// <summary>
        /// Provides access to the underlying input action "DriveControl/shoulderWest".
        /// </summary>
        public InputAction @shoulderWest => m_Wrapper.m_DriveControl_shoulderWest;
        /// <summary>
        /// Provides access to the underlying input action "DriveControl/shoulderEast".
        /// </summary>
        public InputAction @shoulderEast => m_Wrapper.m_DriveControl_shoulderEast;
        /// <summary>
        /// Provides access to the underlying input action "DriveControl/triggerEast".
        /// </summary>
        public InputAction @triggerEast => m_Wrapper.m_DriveControl_triggerEast;
        /// <summary>
        /// Provides access to the underlying input action "DriveControl/triggerWest".
        /// </summary>
        public InputAction @triggerWest => m_Wrapper.m_DriveControl_triggerWest;
        /// <summary>
        /// Provides access to the underlying input action "DriveControl/joystickEastButton".
        /// </summary>
        public InputAction @joystickEastButton => m_Wrapper.m_DriveControl_joystickEastButton;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_DriveControl; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="DriveControlActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(DriveControlActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="DriveControlActions" />
        public void AddCallbacks(IDriveControlActions instance)
        {
            if (instance == null || m_Wrapper.m_DriveControlActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DriveControlActionsCallbackInterfaces.Add(instance);
            @leftJoy.started += instance.OnLeftJoy;
            @leftJoy.performed += instance.OnLeftJoy;
            @leftJoy.canceled += instance.OnLeftJoy;
            @rightJoy.started += instance.OnRightJoy;
            @rightJoy.performed += instance.OnRightJoy;
            @rightJoy.canceled += instance.OnRightJoy;
            @buttonEast.started += instance.OnButtonEast;
            @buttonEast.performed += instance.OnButtonEast;
            @buttonEast.canceled += instance.OnButtonEast;
            @buttonWest.started += instance.OnButtonWest;
            @buttonWest.performed += instance.OnButtonWest;
            @buttonWest.canceled += instance.OnButtonWest;
            @buttonNorth.started += instance.OnButtonNorth;
            @buttonNorth.performed += instance.OnButtonNorth;
            @buttonNorth.canceled += instance.OnButtonNorth;
            @buttonSouth.started += instance.OnButtonSouth;
            @buttonSouth.performed += instance.OnButtonSouth;
            @buttonSouth.canceled += instance.OnButtonSouth;
            @dpadEast.started += instance.OnDpadEast;
            @dpadEast.performed += instance.OnDpadEast;
            @dpadEast.canceled += instance.OnDpadEast;
            @dpadWest.started += instance.OnDpadWest;
            @dpadWest.performed += instance.OnDpadWest;
            @dpadWest.canceled += instance.OnDpadWest;
            @dpadNorth.started += instance.OnDpadNorth;
            @dpadNorth.performed += instance.OnDpadNorth;
            @dpadNorth.canceled += instance.OnDpadNorth;
            @dpadSouth.started += instance.OnDpadSouth;
            @dpadSouth.performed += instance.OnDpadSouth;
            @dpadSouth.canceled += instance.OnDpadSouth;
            @start.started += instance.OnStart;
            @start.performed += instance.OnStart;
            @start.canceled += instance.OnStart;
            @select.started += instance.OnSelect;
            @select.performed += instance.OnSelect;
            @select.canceled += instance.OnSelect;
            @shoulderWest.started += instance.OnShoulderWest;
            @shoulderWest.performed += instance.OnShoulderWest;
            @shoulderWest.canceled += instance.OnShoulderWest;
            @shoulderEast.started += instance.OnShoulderEast;
            @shoulderEast.performed += instance.OnShoulderEast;
            @shoulderEast.canceled += instance.OnShoulderEast;
            @triggerEast.started += instance.OnTriggerEast;
            @triggerEast.performed += instance.OnTriggerEast;
            @triggerEast.canceled += instance.OnTriggerEast;
            @triggerWest.started += instance.OnTriggerWest;
            @triggerWest.performed += instance.OnTriggerWest;
            @triggerWest.canceled += instance.OnTriggerWest;
            @joystickEastButton.started += instance.OnJoystickEastButton;
            @joystickEastButton.performed += instance.OnJoystickEastButton;
            @joystickEastButton.canceled += instance.OnJoystickEastButton;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="DriveControlActions" />
        private void UnregisterCallbacks(IDriveControlActions instance)
        {
            @leftJoy.started -= instance.OnLeftJoy;
            @leftJoy.performed -= instance.OnLeftJoy;
            @leftJoy.canceled -= instance.OnLeftJoy;
            @rightJoy.started -= instance.OnRightJoy;
            @rightJoy.performed -= instance.OnRightJoy;
            @rightJoy.canceled -= instance.OnRightJoy;
            @buttonEast.started -= instance.OnButtonEast;
            @buttonEast.performed -= instance.OnButtonEast;
            @buttonEast.canceled -= instance.OnButtonEast;
            @buttonWest.started -= instance.OnButtonWest;
            @buttonWest.performed -= instance.OnButtonWest;
            @buttonWest.canceled -= instance.OnButtonWest;
            @buttonNorth.started -= instance.OnButtonNorth;
            @buttonNorth.performed -= instance.OnButtonNorth;
            @buttonNorth.canceled -= instance.OnButtonNorth;
            @buttonSouth.started -= instance.OnButtonSouth;
            @buttonSouth.performed -= instance.OnButtonSouth;
            @buttonSouth.canceled -= instance.OnButtonSouth;
            @dpadEast.started -= instance.OnDpadEast;
            @dpadEast.performed -= instance.OnDpadEast;
            @dpadEast.canceled -= instance.OnDpadEast;
            @dpadWest.started -= instance.OnDpadWest;
            @dpadWest.performed -= instance.OnDpadWest;
            @dpadWest.canceled -= instance.OnDpadWest;
            @dpadNorth.started -= instance.OnDpadNorth;
            @dpadNorth.performed -= instance.OnDpadNorth;
            @dpadNorth.canceled -= instance.OnDpadNorth;
            @dpadSouth.started -= instance.OnDpadSouth;
            @dpadSouth.performed -= instance.OnDpadSouth;
            @dpadSouth.canceled -= instance.OnDpadSouth;
            @start.started -= instance.OnStart;
            @start.performed -= instance.OnStart;
            @start.canceled -= instance.OnStart;
            @select.started -= instance.OnSelect;
            @select.performed -= instance.OnSelect;
            @select.canceled -= instance.OnSelect;
            @shoulderWest.started -= instance.OnShoulderWest;
            @shoulderWest.performed -= instance.OnShoulderWest;
            @shoulderWest.canceled -= instance.OnShoulderWest;
            @shoulderEast.started -= instance.OnShoulderEast;
            @shoulderEast.performed -= instance.OnShoulderEast;
            @shoulderEast.canceled -= instance.OnShoulderEast;
            @triggerEast.started -= instance.OnTriggerEast;
            @triggerEast.performed -= instance.OnTriggerEast;
            @triggerEast.canceled -= instance.OnTriggerEast;
            @triggerWest.started -= instance.OnTriggerWest;
            @triggerWest.performed -= instance.OnTriggerWest;
            @triggerWest.canceled -= instance.OnTriggerWest;
            @joystickEastButton.started -= instance.OnJoystickEastButton;
            @joystickEastButton.performed -= instance.OnJoystickEastButton;
            @joystickEastButton.canceled -= instance.OnJoystickEastButton;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="DriveControlActions.UnregisterCallbacks(IDriveControlActions)" />.
        /// </summary>
        /// <seealso cref="DriveControlActions.UnregisterCallbacks(IDriveControlActions)" />
        public void RemoveCallbacks(IDriveControlActions instance)
        {
            if (m_Wrapper.m_DriveControlActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="DriveControlActions.AddCallbacks(IDriveControlActions)" />
        /// <seealso cref="DriveControlActions.RemoveCallbacks(IDriveControlActions)" />
        /// <seealso cref="DriveControlActions.UnregisterCallbacks(IDriveControlActions)" />
        public void SetCallbacks(IDriveControlActions instance)
        {
            foreach (var item in m_Wrapper.m_DriveControlActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DriveControlActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="DriveControlActions" /> instance referencing this action map.
    /// </summary>
    public DriveControlActions @DriveControl => new DriveControlActions(this);

    // BoardControl
    private readonly InputActionMap m_BoardControl;
    private List<IBoardControlActions> m_BoardControlActionsCallbackInterfaces = new List<IBoardControlActions>();
    private readonly InputAction m_BoardControl_Newaction;
    /// <summary>
    /// Provides access to input actions defined in input action map "BoardControl".
    /// </summary>
    public struct BoardControlActions
    {
        private @GameController m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public BoardControlActions(@GameController wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "BoardControl/Newaction".
        /// </summary>
        public InputAction @Newaction => m_Wrapper.m_BoardControl_Newaction;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_BoardControl; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="BoardControlActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(BoardControlActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="BoardControlActions" />
        public void AddCallbacks(IBoardControlActions instance)
        {
            if (instance == null || m_Wrapper.m_BoardControlActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_BoardControlActionsCallbackInterfaces.Add(instance);
            @Newaction.started += instance.OnNewaction;
            @Newaction.performed += instance.OnNewaction;
            @Newaction.canceled += instance.OnNewaction;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="BoardControlActions" />
        private void UnregisterCallbacks(IBoardControlActions instance)
        {
            @Newaction.started -= instance.OnNewaction;
            @Newaction.performed -= instance.OnNewaction;
            @Newaction.canceled -= instance.OnNewaction;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="BoardControlActions.UnregisterCallbacks(IBoardControlActions)" />.
        /// </summary>
        /// <seealso cref="BoardControlActions.UnregisterCallbacks(IBoardControlActions)" />
        public void RemoveCallbacks(IBoardControlActions instance)
        {
            if (m_Wrapper.m_BoardControlActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="BoardControlActions.AddCallbacks(IBoardControlActions)" />
        /// <seealso cref="BoardControlActions.RemoveCallbacks(IBoardControlActions)" />
        /// <seealso cref="BoardControlActions.UnregisterCallbacks(IBoardControlActions)" />
        public void SetCallbacks(IBoardControlActions instance)
        {
            foreach (var item in m_Wrapper.m_BoardControlActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_BoardControlActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="BoardControlActions" /> instance referencing this action map.
    /// </summary>
    public BoardControlActions @BoardControl => new BoardControlActions(this);

    // KeyboardControl
    private readonly InputActionMap m_KeyboardControl;
    private List<IKeyboardControlActions> m_KeyboardControlActionsCallbackInterfaces = new List<IKeyboardControlActions>();
    private readonly InputAction m_KeyboardControl_onekey;
    private readonly InputAction m_KeyboardControl_twokey;
    private readonly InputAction m_KeyboardControl_threekey;
    private readonly InputAction m_KeyboardControl_fourkey;
    private readonly InputAction m_KeyboardControl_fivekey;
    private readonly InputAction m_KeyboardControl_sixkey;
    private readonly InputAction m_KeyboardControl_sevenkey;
    private readonly InputAction m_KeyboardControl_eightkey;
    private readonly InputAction m_KeyboardControl_ninekey;
    private readonly InputAction m_KeyboardControl_zerokey;
    private readonly InputAction m_KeyboardControl_Enter;
    private readonly InputAction m_KeyboardControl_spacekey;
    private readonly InputAction m_KeyboardControl_backspacekey;
    private readonly InputAction m_KeyboardControl_shiftkey;
    /// <summary>
    /// Provides access to input actions defined in input action map "KeyboardControl".
    /// </summary>
    public struct KeyboardControlActions
    {
        private @GameController m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public KeyboardControlActions(@GameController wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "KeyboardControl/onekey".
        /// </summary>
        public InputAction @onekey => m_Wrapper.m_KeyboardControl_onekey;
        /// <summary>
        /// Provides access to the underlying input action "KeyboardControl/twokey".
        /// </summary>
        public InputAction @twokey => m_Wrapper.m_KeyboardControl_twokey;
        /// <summary>
        /// Provides access to the underlying input action "KeyboardControl/threekey".
        /// </summary>
        public InputAction @threekey => m_Wrapper.m_KeyboardControl_threekey;
        /// <summary>
        /// Provides access to the underlying input action "KeyboardControl/fourkey".
        /// </summary>
        public InputAction @fourkey => m_Wrapper.m_KeyboardControl_fourkey;
        /// <summary>
        /// Provides access to the underlying input action "KeyboardControl/fivekey".
        /// </summary>
        public InputAction @fivekey => m_Wrapper.m_KeyboardControl_fivekey;
        /// <summary>
        /// Provides access to the underlying input action "KeyboardControl/sixkey".
        /// </summary>
        public InputAction @sixkey => m_Wrapper.m_KeyboardControl_sixkey;
        /// <summary>
        /// Provides access to the underlying input action "KeyboardControl/sevenkey".
        /// </summary>
        public InputAction @sevenkey => m_Wrapper.m_KeyboardControl_sevenkey;
        /// <summary>
        /// Provides access to the underlying input action "KeyboardControl/eightkey".
        /// </summary>
        public InputAction @eightkey => m_Wrapper.m_KeyboardControl_eightkey;
        /// <summary>
        /// Provides access to the underlying input action "KeyboardControl/ninekey".
        /// </summary>
        public InputAction @ninekey => m_Wrapper.m_KeyboardControl_ninekey;
        /// <summary>
        /// Provides access to the underlying input action "KeyboardControl/zerokey".
        /// </summary>
        public InputAction @zerokey => m_Wrapper.m_KeyboardControl_zerokey;
        /// <summary>
        /// Provides access to the underlying input action "KeyboardControl/Enter".
        /// </summary>
        public InputAction @Enter => m_Wrapper.m_KeyboardControl_Enter;
        /// <summary>
        /// Provides access to the underlying input action "KeyboardControl/spacekey".
        /// </summary>
        public InputAction @spacekey => m_Wrapper.m_KeyboardControl_spacekey;
        /// <summary>
        /// Provides access to the underlying input action "KeyboardControl/backspacekey".
        /// </summary>
        public InputAction @backspacekey => m_Wrapper.m_KeyboardControl_backspacekey;
        /// <summary>
        /// Provides access to the underlying input action "KeyboardControl/shiftkey".
        /// </summary>
        public InputAction @shiftkey => m_Wrapper.m_KeyboardControl_shiftkey;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_KeyboardControl; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="KeyboardControlActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(KeyboardControlActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="KeyboardControlActions" />
        public void AddCallbacks(IKeyboardControlActions instance)
        {
            if (instance == null || m_Wrapper.m_KeyboardControlActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_KeyboardControlActionsCallbackInterfaces.Add(instance);
            @onekey.started += instance.OnOnekey;
            @onekey.performed += instance.OnOnekey;
            @onekey.canceled += instance.OnOnekey;
            @twokey.started += instance.OnTwokey;
            @twokey.performed += instance.OnTwokey;
            @twokey.canceled += instance.OnTwokey;
            @threekey.started += instance.OnThreekey;
            @threekey.performed += instance.OnThreekey;
            @threekey.canceled += instance.OnThreekey;
            @fourkey.started += instance.OnFourkey;
            @fourkey.performed += instance.OnFourkey;
            @fourkey.canceled += instance.OnFourkey;
            @fivekey.started += instance.OnFivekey;
            @fivekey.performed += instance.OnFivekey;
            @fivekey.canceled += instance.OnFivekey;
            @sixkey.started += instance.OnSixkey;
            @sixkey.performed += instance.OnSixkey;
            @sixkey.canceled += instance.OnSixkey;
            @sevenkey.started += instance.OnSevenkey;
            @sevenkey.performed += instance.OnSevenkey;
            @sevenkey.canceled += instance.OnSevenkey;
            @eightkey.started += instance.OnEightkey;
            @eightkey.performed += instance.OnEightkey;
            @eightkey.canceled += instance.OnEightkey;
            @ninekey.started += instance.OnNinekey;
            @ninekey.performed += instance.OnNinekey;
            @ninekey.canceled += instance.OnNinekey;
            @zerokey.started += instance.OnZerokey;
            @zerokey.performed += instance.OnZerokey;
            @zerokey.canceled += instance.OnZerokey;
            @Enter.started += instance.OnEnter;
            @Enter.performed += instance.OnEnter;
            @Enter.canceled += instance.OnEnter;
            @spacekey.started += instance.OnSpacekey;
            @spacekey.performed += instance.OnSpacekey;
            @spacekey.canceled += instance.OnSpacekey;
            @backspacekey.started += instance.OnBackspacekey;
            @backspacekey.performed += instance.OnBackspacekey;
            @backspacekey.canceled += instance.OnBackspacekey;
            @shiftkey.started += instance.OnShiftkey;
            @shiftkey.performed += instance.OnShiftkey;
            @shiftkey.canceled += instance.OnShiftkey;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="KeyboardControlActions" />
        private void UnregisterCallbacks(IKeyboardControlActions instance)
        {
            @onekey.started -= instance.OnOnekey;
            @onekey.performed -= instance.OnOnekey;
            @onekey.canceled -= instance.OnOnekey;
            @twokey.started -= instance.OnTwokey;
            @twokey.performed -= instance.OnTwokey;
            @twokey.canceled -= instance.OnTwokey;
            @threekey.started -= instance.OnThreekey;
            @threekey.performed -= instance.OnThreekey;
            @threekey.canceled -= instance.OnThreekey;
            @fourkey.started -= instance.OnFourkey;
            @fourkey.performed -= instance.OnFourkey;
            @fourkey.canceled -= instance.OnFourkey;
            @fivekey.started -= instance.OnFivekey;
            @fivekey.performed -= instance.OnFivekey;
            @fivekey.canceled -= instance.OnFivekey;
            @sixkey.started -= instance.OnSixkey;
            @sixkey.performed -= instance.OnSixkey;
            @sixkey.canceled -= instance.OnSixkey;
            @sevenkey.started -= instance.OnSevenkey;
            @sevenkey.performed -= instance.OnSevenkey;
            @sevenkey.canceled -= instance.OnSevenkey;
            @eightkey.started -= instance.OnEightkey;
            @eightkey.performed -= instance.OnEightkey;
            @eightkey.canceled -= instance.OnEightkey;
            @ninekey.started -= instance.OnNinekey;
            @ninekey.performed -= instance.OnNinekey;
            @ninekey.canceled -= instance.OnNinekey;
            @zerokey.started -= instance.OnZerokey;
            @zerokey.performed -= instance.OnZerokey;
            @zerokey.canceled -= instance.OnZerokey;
            @Enter.started -= instance.OnEnter;
            @Enter.performed -= instance.OnEnter;
            @Enter.canceled -= instance.OnEnter;
            @spacekey.started -= instance.OnSpacekey;
            @spacekey.performed -= instance.OnSpacekey;
            @spacekey.canceled -= instance.OnSpacekey;
            @backspacekey.started -= instance.OnBackspacekey;
            @backspacekey.performed -= instance.OnBackspacekey;
            @backspacekey.canceled -= instance.OnBackspacekey;
            @shiftkey.started -= instance.OnShiftkey;
            @shiftkey.performed -= instance.OnShiftkey;
            @shiftkey.canceled -= instance.OnShiftkey;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="KeyboardControlActions.UnregisterCallbacks(IKeyboardControlActions)" />.
        /// </summary>
        /// <seealso cref="KeyboardControlActions.UnregisterCallbacks(IKeyboardControlActions)" />
        public void RemoveCallbacks(IKeyboardControlActions instance)
        {
            if (m_Wrapper.m_KeyboardControlActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="KeyboardControlActions.AddCallbacks(IKeyboardControlActions)" />
        /// <seealso cref="KeyboardControlActions.RemoveCallbacks(IKeyboardControlActions)" />
        /// <seealso cref="KeyboardControlActions.UnregisterCallbacks(IKeyboardControlActions)" />
        public void SetCallbacks(IKeyboardControlActions instance)
        {
            foreach (var item in m_Wrapper.m_KeyboardControlActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_KeyboardControlActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="KeyboardControlActions" /> instance referencing this action map.
    /// </summary>
    public KeyboardControlActions @KeyboardControl => new KeyboardControlActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "DriveControl" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="DriveControlActions.AddCallbacks(IDriveControlActions)" />
    /// <seealso cref="DriveControlActions.RemoveCallbacks(IDriveControlActions)" />
    public interface IDriveControlActions
    {
        /// <summary>
        /// Method invoked when associated input action "leftJoy" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLeftJoy(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "rightJoy" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRightJoy(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "buttonEast" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnButtonEast(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "buttonWest" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnButtonWest(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "buttonNorth" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnButtonNorth(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "buttonSouth" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnButtonSouth(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "dpadEast" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDpadEast(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "dpadWest" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDpadWest(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "dpadNorth" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDpadNorth(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "dpadSouth" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDpadSouth(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "start" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnStart(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "select" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSelect(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "shoulderWest" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnShoulderWest(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "shoulderEast" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnShoulderEast(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "triggerEast" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTriggerEast(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "triggerWest" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTriggerWest(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "joystickEastButton" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnJoystickEastButton(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "BoardControl" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="BoardControlActions.AddCallbacks(IBoardControlActions)" />
    /// <seealso cref="BoardControlActions.RemoveCallbacks(IBoardControlActions)" />
    public interface IBoardControlActions
    {
        /// <summary>
        /// Method invoked when associated input action "New action" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnNewaction(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "KeyboardControl" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="KeyboardControlActions.AddCallbacks(IKeyboardControlActions)" />
    /// <seealso cref="KeyboardControlActions.RemoveCallbacks(IKeyboardControlActions)" />
    public interface IKeyboardControlActions
    {
        /// <summary>
        /// Method invoked when associated input action "onekey" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnOnekey(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "twokey" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTwokey(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "threekey" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnThreekey(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "fourkey" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnFourkey(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "fivekey" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnFivekey(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "sixkey" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSixkey(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "sevenkey" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSevenkey(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "eightkey" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnEightkey(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ninekey" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnNinekey(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "zerokey" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnZerokey(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Enter" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnEnter(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "spacekey" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSpacekey(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "backspacekey" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnBackspacekey(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "shiftkey" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnShiftkey(InputAction.CallbackContext context);
    }
}
